[package]
name = 'testbuild'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'testbuild'

[dependencies]
extendr-api = '*'
polars = {version = "0.36.2", features = ["csv", "lazy"]}