# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_testbuild_wrappers", use_symbols = TRUE, package_name = "testbuild")

#' @docType package
#' @usage NULL
#' @useDynLib testbuild, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Verify that the build system worked.
#' @export
verify_install <- function() .Call(wrap__verify_install)


# nolint end
