name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("rextendr", "devtools"))'
        Rscript -e 'remotes::install_cran("roxygen2")'

    - name: Build and Document
      run: |
        Rscript .github/util/package_build_script.R

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-artifacts-${{ runner.os }}
        path: build/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Release Artifacts
      uses: actions/download-artifact@v2
      with:
        name: release-artifacts-Windows
        path: binaries

    - name: Download Release Artifacts
      uses: actions/download-artifact@v2
      with:
        name: release-artifacts-macOS
        path: binaries        

    - name: Extract version
      id: extract_version
      run: |
        VERSION=$(sed -n '3p' DESCRIPTION)
        VERSION=${VERSION#*: }
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ env.VERSION }}
        body: Pre-built package binaries for version ${{ env.VERSION }}
        files: 'binaries/*'
        draft: false
        prerelease: false
